export const cars = [
  {
    id: "CID0000002",
    name: "Maruti Alto K10",
    fuel: "Diesel",
    qc: "Approved",
    auction: "Pending",
    status: "Approved",
  },
  {
    id: "CID0000003",
    name: "Dummy Car 2",
    fuel: "Electric",
    qc: "Rejected",
    auction: "Pending",
    status: "Pending",
  },
  {
    id: "CID0000004",
    name: "Dummy Car 3",
    fuel: "Hybrid",
    qc: "Approved",
    auction: "Rejected",
    status: "Rejected",
  },
  {
    id: "CID0000005",
    name: "Dummy Car 4",
    fuel: "Petrol",
    qc: "Approved",
    auction: "Pending",
    status: "Approved",
  },
  {
    id: "CID0000006",
    name: "Dummy Car 5",
    fuel: "Diesel",
    qc: "Pending",
    auction: "Approved",
    status: "Pending",
  },
  {
    id: "CID0000007",
    name: "Dummy Car 6",
    fuel: "Electric",
    qc: "Rejected",
    auction: "Pending",
    status: "Rejected",
  },
  {
    id: "CID0000008",
    name: "Dummy Car 7",
    fuel: "Hybrid",
    qc: "Approved",
    auction: "Rejected",
    status: "Approved",
  },
  {
    id: "CID0000009",
    name: "Dummy Car 8",
    fuel: "Petrol",
    qc: "Pending",
    auction: "Approved",
    status: "Pending",
  },
  {
    id: "CID0000010",
    name: "Dummy Car 9",
    fuel: "Diesel",
    qc: "Rejected",
    auction: "Pending",
    status: "Rejected",
  },
  {
    id: "CID0000011",
    name: "Dummy Car 10",
    fuel: "Electric",
    qc: "Approved",
    auction: "Rejected",
    status: "Approved",
  },
];
